config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'

  resources :lists

  get 'list/pop' => 'lists#pop'
  get 'list/natural' => 'lists#natural'
  get 'list/elegant' => 'lists#elegant'

  resources :words


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/word.rb
class Word < ApplicationRecord
  
  validates :english, presence: true
  validates :japanese, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
  end

  def pop
    @words = Word.order("RANDOM()").limit(1)
  end

  def elegant
    @words = Word.all
  end

  def natural
    @words_random = Word.order("RANDOM()").limit(5)
  end


end

app/controllers/words_controller.rb
class WordsController < ApplicationController


  def new
    @word = Word.new
  end

  def index
    @words = Word.all
  end

  def show
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      flash[:success] = "投稿が完了しました。"
      redirect_to words_path
    else
      flash.now[:warning] = "投稿に失敗しました。項目を埋めてください。"
      render "new"
    end
  end

  def destroy
    @word = Word.find(params[:id])
    if @word.destroy
      flash[:success] = "投稿は削除されました。"
      redirect_to words_path
    end
  end

  private

  def word_params
    params.require(:word).permit(:english, :japanese)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/homes/top.html.erb
top

<%= link_to 'index', lists_path, class: '' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Design</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/elegant.html.erb
<div class="header-elegant"></div>
<div class="elegant-body">
  <div class="elegant-top"></div>
  スモーキーパープル#dbcbc7
  ダルネスパープル#7f5072
  ディープレイク#acb0a8




  <%= link_to "word", new_word_path, class: "" %>



  <div class="elegant-main">
    <div class="word-list">
      <table class="table">
        <thead>
        <th>English</th>
        <th>日本語</th>
        </thead>
        <% @words.each do |word| %>
          <tbody>
          <td><%= word.english %></td>
          <td><%= word.japanese %></td>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>



</div>
<div class="footer-elegant"></div>

app/views/lists/index.html.erb
index

デザインリスト


<li>
  <%= link_to "pop", list_pop_path, class: "btn" %>
  <%= link_to "natural", list_natural_path, class: "btn" %>
  <%= link_to "elegant", list_elegant_path, class: "btn" %>
  <%= link_to "word_index", words_path, class: "btn btn-primary" %>
</li>

app/views/lists/natural.html.erb
<div class="header-natural"></div>
<div class="natural-body">


  キャラメルクリーム#e4c6a6
  バフブラウン#8e775d
  ラクダベージュ#e6cd8c
  <div class="natural-main">
    <div class="word-random">
      <% @words_random.each do |word| %>
        <div class="word-english">
          <%= word.english %>
        </div>
        <div class="word-japanese">
          <%= word.japanese %>
        </div>
      <% end %>
    </div>
  </div>


  <%= link_to "next", list_natural_path, class: "btn btn-primary" %>


</div>
<div class="footer-natural"></div>

app/views/lists/pop.html.erb
<div class="pop-body">
<div class="header-pop"></div>

  <!--クリアエール#c0e4f2-->
  <!--プレシャスクレイ#ded3d6-->
  <!--ベイビーシープ#fffcd7-->
  <div class="pop-main">
    <h1 class="pop-title">English Test</h1>
    <h3>3秒後に日本語訳が表示されます</h3>
    <div class="pop-test">
      <% @words.each do |word| %>
      <%= word.english %>
      <div class="word-japanese">
      <%= word.japanese %>
      </div>
      <% end %>
    </div>
  </div>




<div class="footer-pop"></div>
</div>

app/views/words/index.html.erb
<div class="header-elegant"></div>
<div class="elegant-body">
  <div class="elegant-top"></div>
  スモーキーパープル#dbcbc7
  ダルネスパープル#7f5072
  ディープレイク#acb0a8




  <%= link_to "word", new_word_path, class: "" %>
  <%= flash[:success] %>



  <div class="elegant-main">
    <div class="word-list">
      <table class="table">
        <thead>
        <th>English</th>
        <th>日本語</th>
        <th></th>
        </thead>
        <% @words.each do |word| %>
          <tbody>
          <td><%= word.english %></td>
          <td><%= word.japanese %></td>
          <td><%= link_to "delete", word_path(word), method: :delete, class: "btn btn-danger" %></td>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>



</div>
<div class="footer-elegant"></div>

app/views/words/new.html.erb
  <%= flash[:warning] %>

  <div class="word-form">
    <%= form_with model:@word, local:true do |f| %>
    <%= f.text_field :english %>
    <%= f.text_field :japanese %>
    <%= f.submit '投稿' %>
    <% end %>
  </div>